apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-convtemp
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: web
    template:
      metadata:
        labels:
          app: web
      spec:
        containers:
        - name: site
          image: fabricioveronez/conversao-temperatura:v1
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-convtemp
spec:
  selector:
    app: web
  ports:
    - port: 80
      protocol: TCP
type: NodePort